"""add chat table

Revision ID: 1c48bd2274ea
Revises: 178b9fff7361
Create Date: 2026-03-24 03:45:01.686371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c48bd2274ea'
down_revision: Union[str, Sequence[str], None] = '178b9fff7361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###

