"""create raw_texts table

Revision ID: 1e9780771a87
Revises: 1c48bd2274ea
Create Date: 2026-03-24 05:09:09.448741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e9780771a87'
down_revision: Union[str, Sequence[str], None] = '1c48bd2274ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table("upload_files",
    sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),
    sa.Column('filename', sa.VARCHAR(255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(255), nullable=False),
    sa.Column('size', sa.BigInteger(), default=0),
    sa.Column('status', sa.Integer(), default=1),
    sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )


    op.create_table('raw_texts',
    sa.Column('id', sa.BigInteger(), primary_key=True),
    sa.Column('upload_file_id', sa.BigInteger(), nullable=False),
    sa.Column('parse_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chunk_size', sa.Integer(), default=800),
    sa.Column('chunk_overlap', sa.Integer(), default=100),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), primary_key=True),
    sa.Column('upload_file_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.VARCHAR(length=26), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('raw_texts')
    op.drop_table('upload_files')
    # ### end Alembic commands ###
